name: CMake workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  INTERFACE_TYPE_ARCHON: Archon
  INTERFACE_TYPE_ASTROCAM: AstroCam
  INSTR: generic

jobs:
  build-archon:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependecies
      run: |
        sudo apt-get update
        sudo apt-get install libccfits-dev
        sudo apt-get install libcfitsio-dev
        sudo apt-get install libcurl4-openssl-dev
    
    - name: Configure CMake Archon
      run: |
        cd ${{github.workspace}}/build
        rm -rf * 
        cmake -DINTERFACE_TYPE=${{env.INTERFACE_TYPE_ARCHON}} -DINSTR=${{env.INSTR}} ..

    - name: Build Archon
      # Build your program with the given configuration
      run: |
        cd ${{github.workspace}}/build
        make
  
  build-astrocam:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependecies
      run: |
        sudo apt-get update
        sudo apt-get install libccfits-dev
        sudo apt-get install libcfitsio-dev
        sudo apt-get install libcurl4-openssl-dev

    - name: Configure CMake AstroCam
      run: |
        cd ${{github.workspace}}/build
        rm -rf * 
        cmake -DINTERFACE_TYPE=${{env.INTERFACE_TYPE_ASTROCAM}} -DINSTR=${{env.INSTR}} ..

    - name: Build AstroCam
      # Build your program with the given configuration
      run: |
        cd ${{github.workspace}}/build
        make

