name: CMake workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  INTERFACE_TYPE_ARCHON: Archon
  INTERFACE_TYPE_ASTROCAM: AstroCam

jobs:
  Archon:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependecies
      run: |
        ls -l
        .github/workflows/install-deps.sh
      shell: bash
    
    - name: Configure CMake Archon
      run: |
        cd ${{github.workspace}}/build
        rm -rf *
        g++ --version
        cmake -DINTERFACE_TYPE=${{env.INTERFACE_TYPE_ARCHON}} ..

    - name: Build Archon
      # Build your program with the given configuration
      run: |
        cd ${{github.workspace}}/build
        make

    - name: Start Emulator
      run: |
        cd ${{github.workspace}}
        bin/emulator Config/demo/demo.cfg &

    - name: Start camera-daemon
      run: |
        cd ${{github.workspace}}
        bin/camerad Config/demo/demo.cfg --foreground &

    - name: Run test commands
      run: |
        cd ${{github.workspace}}
        shopt -s expand_aliases
        alias cam="bin/socksend -h localhost -p 3031"
        function check { if [ $1 != "DONE" ]; then echo $1; exit 1; else echo $1; fi }
        
        command_open=$(cam open)
        check $command_open
        
        command_load=$(cam load)
        check $command_load
        
        # command_exptime=$(cam exptime 1500)
        # check $command_exptime
        
        command_expose=$(cam expose)
        check $command_expose
        
        command_printstatus=$(cam printstatus)
        check $command_printstatus

  # Comment AstroCam out for now
  # build-astrocam:
  #   runs-on: ubuntu-20.04

  #   steps:
  #   - uses: actions/checkout@v4

  #   - name: Install dependecies
  #     run: .github/workflows/install-deps.sh
  #     shell: bash

  #   - name: Install ARC64PCI
  #     run: |
  #       cd ${{github.workspace}}/..
  #       git clone https://github.com/CaltechOpticalObservatories/Arc64PCI.git
  #       cd Arc64PCI
  #       g++ --version
  #       make

  #   - name: Install ARC-API
  #     run: |
  #       cd ${{github.workspace}}/..
  #       git clone https://github.com/CaltechOpticalObservatories/ARC_API_36.git
  #       cd ARC_API_36
  #       g++ --version
  #       make

  #   - name: Configure CMake AstroCam
  #     run: |
  #       cd ${{github.workspace}}/build
  #       rm -rf * 
  #       cmake -DINTERFACE_TYPE=${{env.INTERFACE_TYPE_ASTROCAM}} ..

  #   - name: Build AstroCam
  #     # Build your program with the given configuration
  #     run: |
  #       cd ${{github.workspace}}/build
  #       make

